# Generated by Django 4.2.4 on 2023-08-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0002_alter_receipe_receipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipe',
            name='receipe_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
